### ISSUE TITLE
Onboarding process of Maxence Guindon

### ISSUE THREAD

**Issue by MaxenceGui** [ai-cfia/dev-rel-docs#105]
Maxence Guindon onboarding process

Tasks:

* [ ] Update time descriptions.

Acceptance Criteria:

The training should equip the developer with the skills necessary to work within the AI LAB's framework.
The training should provide accurate time estimates for each module.

**Comment by MaxenceGui** [comment]
@ibrahim-kabir the link to postgresML exercise link to their home page. Is it normal?

**Comment by ibrahim-kabir** [comment]
> @ibrahim-kabir the link to postgresML exercise link to their home page. Is it normal?

Yes, I couldn't link it to the notebooks tab since it's only accessible when logged in with your PostgreML account. It caused a link check error. 

You could add steps to clarify, for example:

Log in to [PostgreML Tutorials](https://postgresml.org/) and complete all the tutorials on the Notebooks tab
